[project]
name = "goit-algo-hw-10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pulp>=3.3.0",
    "scipy>=1.16.3",
]
